### PR TITLE
Fix travis build

### PR DESCRIPTION
**Pull request by arturcic**
Fixed the travis build. [travis build](https://travis-ci.org/arturcic/GitVersion/builds/382571464)

Appveyour works as well [appveyour build](https://ci.appveyor.com/project/arturcic/gitversion/build/4.0.0-netstandard.1+1577.build.2)

### CODE REVIEW

**Comment by dazinator** [comment]
Have taken a look. With the change to `msbuild` does this mean that we are back to using `mono` on linux in order to build? Or does `msbuild` on linux use dotnet core? Wondering if `mono` can be removed :-)

**Comment by dazinator** [comment]
I think it's probably safe to merge this given you have fixed the broken travis build and added the test filter! We can work out the mono dependency stuff seperately later.

**Comment by arturcic** [comment]
It's using the msbuild on each platform

https://github.com/cake-build/cake/blob/develop/src/Cake.Common/Tools/MSBuild/MSBuildResolver.cs

**Comment by dazinator** [comment]
Thanks - so looking at that it does seem to depend on mono: https://github.com/cake-build/cake/blob/develop/src/Cake.Common/Tools/MSBuild/MSBuildResolver.cs#L17

Msbuild is also available under .net core now: https://github.com/Microsoft/msbuild which means a mono install would be unnecessary - something we can look at seperately later.

**Pull request merged**
